export default function HomePage() {
    return (
    <div className="homepage">
        Namaste!
        <div>
        <label>Name your board</label>
        <input placeholder="name your board..."></input>
        </div>
        _________________________________________________
        <br/>
        (Click on any paragraph below to highlight features inside of the tool panel)

        <ul>
        <li>Choose a theme</li>
        <li>Generate a quote or....</li>
        <li>add your own</li>
        <li>Write your affirmations</li>
        <li>Add images for visualization</li>
        <li>Add stickers</li>
        <li>Clear/ Save or Edit your Board</li>
        <li>Download your board as an image</li>
        <li>Come back here for reference any time if you forgot something</li>
        <li>***Placeholder for autogenerated inspirational quote***</li>
        </ul>
        </div>
    );
  }