// import {useSelector} from 'react-redux'
import { useState } from "react";
import { useDrag } from '@use-gesture/react'
export default function HomePage() {
    const [logoPos, setLogoPos] = useState({
        x: 0,
        y: 0
    })
    const bindLogoPos = useDrag((params)=>{
            setLogoPos({
                x: params.offset[0],
                y: params.offset[1]
            })
    })
    return (
    <div className="homepage">
        Namaste!
        Welcome to Dream-Create-Receive
        <div>
        <div {...bindLogoPos()} style={{position: "relative", top: logoPos.y, left: logoPos.x}}> 
      <img className="App-logo" src="https://live.staticflickr.com/65535/51508747110_13a7864a12_s.jpg" alt="sticker"></img> 
    </div>
        <div>Water || Eart || Air || Fire</div>
        </div>
        _________________________________________________
        <br/>
        (Click on any paragraph below to highlight features inside of the tool panel)

        <ul>
       
        <li>Generate a quote or....</li>
        <li>add your own</li>
        <li>Write your affirmations</li>
        <li>Add images for visualization</li>
        <li>Add stickers</li>
        <li>Clear/ Save or Edit your Board</li>
        <li>Download your board as an image</li>
        <li>Come back here for reference any time if you forgot something</li>
        <li>***Placeholder for autogenerated inspirational quote***</li>
        </ul>
        </div>
    );
  }